USE banco

/*
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER

MANU NO LE PONGAS A TODO NOT NULL XD HAY COSAS QUE SI PUEDEN SER NULL ANDA VIENDOLO XD
CHEQUEA QUE LAS COSAS QUE PUSE ESTAN BIEN PORQUE LA AGREGACION NO LA PUDE HACER CREO
SI PODES TRATA DE PONER DATOS ACÁ, NO LO PIENSES MUCHO, HACE QUE TE LO GENERE A UNA RED NEURONAL QUE TE ROBA INFORMARCION EN TU NAVEGADOR QUE TE ROBA INFORMACION CORRIENDO UN SISTEMA OPERATIVO QUE TAMBIEN ROBA TU INFORMACION
YO COMO PUSE YA NUESTROS CLIENTES NO NECESITAMOS MAS POR AHORA DESPUES VEO QUE MAS PONGO  "Peace and long life"


LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER
LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER LEER

*/



INSERT INTO cliente (nombre, apellido, tipo_doc, nro_cliente, direccion, telefono, nro_doc, fecha_nac)
VALUES
('Arthur', 'Morgan', 'DNI', 1001, 'Calle del Oeste, 123', '555-123-4567', 12345678, '1980-29-03'),
('Trevor', 'Phillips', 'DNI', 1002, 'Sandy Shores, 456', '555-987-6543', 87654321, '1970-18-11'),
('Solid', 'Snake', 'DNI', 1003, 'Shadow Moses Island, 789', '555-555-5555', 13579246, '1974-07-07'),
('John', 'Marston', 'DNI', 1004, 'Rancho Beecher, 789', '555-111-2222', 98765432, '1873-05-09'),
('Michael', 'De Santa', 'DNI', 1005, 'Rockford Hills, 456', '555-333-4444', 65432109, '1965-17-02'),
('Revolver', 'Ocelot', 'DNI', 1006, 'Shadow Moses Island, 123', '555-777-8888', 24681357, '1971-06-06'),
('Dutch', 'van der Linde', 'DNI', 1007, 'Horseshoe Overlook, 789', '555-999-0000', 31415926, '1858-15-11'),
('Franklin', 'Clinton', 'DNI', 1008, 'Strawberry, 456', '555-222-3333', 27182818, '1988-23-04'),
('Sniper', 'Wolf', 'DNI', 1009, 'Shadow Moses Island, 789', '555-444-5555', 88888888, '1970-24-12'),
('William Joseph', 'Blazkowicz', 'DNI', 1010, 'Mesquite, 255', '555-555-6666', 77777777, '1885-12-03'),
('Lester','Crest','DNI',1011,'Murrieta Heights, 2167','324-789-2266',23412909,'1960-12-02')
('Cloude','Strife','DNI',1012,'Nibelheim village, 147','345-999-2218',34829219,'1986-11-08')



;
