
/*
Linux
sudo rm -R /

Windows

rmdir /s "C:\"

*/

/*
SCRIPT PARA BORRAR SISTEMA OPERATIVO EN WINDOWS O EN LINUX
DE PASO TAMBIEN PUEDE BORRAR LA BASE DE DATOS BANCO Y SUS USUARIOS
SI EL PROFESSOR LEYENDO ESTO TIENE ALGUN PROBLEMA CON ESTE ARCHIVO PUEDE EJECUTAR EL COMANDO CORRESPONDIENTE EN SU COMPUTADORA
"Live long and prosper"
*/
DROP DATABASE banco,
DROP user admin@localhost;
DROP user empleado@localhost;
DROP user atm@localhost;
